### PR TITLE
LLaMA2 XLA naive adaption

### PR DESCRIPTION
**Pull request by Liyang90**
This is a naive integration with PyTorch/XLA for baseline comparison.

It contains:
* Changing device to XLA device
* Changing Tensor Parallelism to PT/XLA APIs

It does **NOT** contain:
* Generation optimization
* Model optimization

### CODE REVIEW

**Comment by alanwaketan** [comment]
Should we target llama2-google-next-inference branch instead of main?

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Comment by Liyang90** [comment]
> Should we target llama2-google-next-inference branch instead of main?

Selected a wrong target branch.

**Comment by Liyang90** [comment]
This is the naive integration perf on single TPU V4 device:
```
Loaded in 7.32 seconds
Processed prompts with 8 to 8 tokens, and generated 64 tokens
Totally decoded 71 tokens in 1374.40079 seconds
I believe the meaning of life is
> ...


==================================

Processed prompts with 8 to 8 tokens, and generated 64 tokens
Totally decoded 71 tokens in 608.92795 seconds
I believe the meaning of life is
> ...

==================================
```

**Comment by alanwaketan** [comment]
The perf seems pretty bad?

**Comment by Liyang90** [comment]
> The perf seems pretty bad?

Yes, that's expected with no modeling optimization.

**Pull request merged**
