### PR TITLE
Llama2 gpu google next inference

### PR DESCRIPTION
**Pull request by cowanmeg**
Merging in the GPU changes. 
Confirmed that all GPU changes are wrapped and do not affect TPU. Following test was run on v4-8.
When running on GPUs add ‘gpu: true’ is added to params.json to enable these changes.

No quantization:
Branch: llama2-google-next-inference
$PJRT_DEVICE=TPU python3 example_text_completion.py --ckpt_dir ~/ckpt/13b --tokenizer_path ~/llama1/t5_tokenizer/spiece.model --max_seq_len 2048 --max_gen_len 1000 --max_batch_size 12 --mp True --dynamo True
Cold:
Processed prompts with 8 to 8 tokens, and generated 1000 tokens
Totally decoded 1007 tokens in 135.18263 seconds
Warm:
Processed prompts with 8 to 8 tokens, and generated 1000 tokens
Totally decoded 1007 tokens in 28.06329 seconds

Branch: llama2-gpu-google-next-inference
$ PJRT_DEVICE=TPU python3 example_text_completion.py --ckpt_dir ~/ckpt/13b --tokenizer_path ~/llama1/t5_tokenizer/spiece.model --max_seq_len 2048 --max_gen_len 1000 --max_batch_size 12 --mp True --dynamo True
Cold:
Processed prompts with 8 to 8 tokens, and generated 1000 tokens
Totally decoded 1007 tokens in 134.80040 seconds
Warm
Processed prompts with 8 to 8 tokens, and generated 1000 tokens
Totally decoded 1007 tokens in 28.12496 seconds

With quantization
Branch: llama2-google-next-inference
$PJRT_DEVICE=TPU python3 example_text_completion.py --ckpt_dir ~/ckpt/13b --tokenizer_path ~/llama1/t5_tokenizer/spiece.model --max_seq_len 2048 --max_gen_len 1000 --max_batch_size 12 --mp True --dynamo True
Cold
Processed prompts with 8 to 8 tokens, and generated 1000 tokens
Totally decoded 1007 tokens in 156.66985 seconds
Warm:
Processed prompts with 8 to 8 tokens, and generated 1000 tokens
Totally decoded 1007 tokens in 27.43947 seconds

Branch: llama2-gpu-google-next-inference
$ PJRT_DEVICE=TPU python3 example_text_completion.py --ckpt_dir ~/ckpt/13b --tokenizer_path ~/llama1/t5_tokenizer/spiece.model --max_seq_len 2048 --max_gen_len 1000 --max_batch_size 12 --mp True --dynamo True

Cold:
Processed prompts with 8 to 8 tokens, and generated 1000 tokens
Totally decoded 1007 tokens in 160.68077 seconds
Warm: 
Processed prompts with 8 to 8 tokens, and generated 1000 tokens
Totally decoded 1007 tokens in 27.49051 seconds

### CODE REVIEW

**Comment by Liyang90** [comment]
Is the gpu config flag for both XLA gpu and cuda gpu?

**Comment by cowanmeg** [comment]
> Is the gpu config flag for both XLA gpu and cuda gpu?

Yes.

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Review by ManfeiBai — APPROVED** [review]
LGTM

**Pull request merged**
